USE BD_SHOPMI;

---------------------------------------
--  		    USUARIO			     --
--------------------------------------

-- GET BY ID
DELIMITER $$
CREATE PROCEDURE USP_GET_ID_USUARIO(IN CODUSUARIO INT)
BEGIN
	SELECT
		U.CODUSUARIO,
		U.NUMERODOCUMENTO,
		U.APEUSUARIO,
		U.NOMUSUARIO,
		U.FECNAC,
		U.SEXUSUARIO,
		U.TELUSUARIO,
		U.CORUSUARIO,
		U.CONUSUARIO,
		U.FECCRE,
		U.ESTUSUARIO,
		R.NOMBREROL AS ROL
	FROM USUARIO AS U
	INNER JOIN ROL R ON U.CODROL = R.CODROL
	WHERE U.CODUSUARIO = CODUSUARIO;
END$$

-- CALL USP_GET_ID_USUARIO(3) ;

-- GET BY CORREO
CREATE PROCEDURE USP_GET_USER_CORREO(IN Correo VARCHAR(80))
BEGIN
	SELECT 
		CODUSUARIO AS Id,
		NUMERODOCUMENTO AS NumeroDocumento,
		NOMUSUARIO AS Nombre,
		APEUSUARIO AS Apellido,
		FECNAC AS FechaNacimiento,
		SEXUSUARIO AS Sexo,
		TELUSUARIO AS Telefono,
		CORUSUARIO AS Email,
		CONUSUARIO AS PasswordHash,
		CODROL AS RolId
	FROM USUARIO U
	WHERE UPPER(CORUSUARIO) = UPPER(Correo);
END$$
-- CALL USP_GET_USER_CORREO('SABRINA@GMAIL.COM');


-- GET BY DNI
CREATE PROCEDURE USP_GET_USER_DNI(IN NUMERODOCUMENTO CHAR(8))
BEGIN
	SELECT 
		CODUSUARIO AS Id,
		NUMERODOCUMENTO AS NumeroDocumento,
		NOMUSUARIO AS Nombre,
		APEUSUARIO AS Apellido,
		FECNAC AS FechaNacimiento,
		SEXUSUARIO AS Sexo,
		TELUSUARIO AS Telefono,
		CORUSUARIO AS Email,
		CONUSUARIO AS PasswordHash,
		CODROL AS RolId
	FROM USUARIO U
	WHERE U.NUMERODOCUMENTO = NUMERODOCUMENTO;
END$$
-- CALL USP_GET_USER_DNI('70448577');

-- INSERT
CREATE PROCEDURE USP_INSERT_USER(
	IN NumeroDocumento CHAR(8),
	IN Apellido VARCHAR(50),
	IN Nombre VARCHAR(50),
	IN FechaNacimiento DATE,
	IN Sexo CHAR(1),
	IN Telefono CHAR(9),
	IN Correo VARCHAR(80),
	IN PasswordHash VARCHAR(100),
	IN Estado BIT,
	IN RolId INT,
	OUT NuevoId INT
)
BEGIN
	INSERT INTO USUARIO (
		NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC,
		SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO,
		ESTUSUARIO, CODROL
	)
	VALUES (
		NumeroDocumento, Apellido, Nombre, FechaNacimiento,
		Sexo, Telefono, Correo, PasswordHash,
		Estado, RolId
	);
	SET NuevoId = LAST_INSERT_ID();
END$$
-- SET @NuevoId = 0;
-- CALL USP_INSERT_USER('70558644', 'Reyna', 'Sabrina', '2003-02-02', 'M', '951565955', 'sabrina@gmail.com', 'Sabrinaix', 1, 1, @NuevoId);
-- SELECT @NuevoId AS NuevoUsuario;


---------------------------------------
--  		    CATEGORIA   	     --
---------------------------------------

-- SELECT

CREATE PROCEDURE USP_SELECT_CATEGORIAS()
BEGIN
	SELECT 
		CA.CODCATEGORIA AS `Value`,
		CA.NOMCATEGORIA AS `Name`
	FROM CATEGORIA AS CA;
END$$

-- GET ALL
CREATE PROCEDURE USP_GET_CATEGORIA()
BEGIN
	SELECT 
		CA.CODCATEGORIA,
		CA.IMGCATEGORIA,
		CA.NOMCATEGORIA,
		CA.ESTCATEGORIA
	FROM CATEGORIA AS CA;
END$$

-- CALL USP_GET_CATEGORIA();

-- GET BY ID
CREATE PROCEDURE USP_GET_ID_CATEGORIA(IN CODCATEGORIA INT)
BEGIN
	SELECT 
		CA.CODCATEGORIA,
		CA.IMGCATEGORIA,
		CA.NOMCATEGORIA
	FROM CATEGORIA AS CA
	WHERE CA.CODCATEGORIA = CODCATEGORIA;
END$$
-- CALL USP_GET_ID_CATEGORIA(2);

---------------------------------------
--  		   MARCA        	     --
--------------------------------------- 

-- SELECT
CREATE PROCEDURE USP_SELECT_MARCAS()
BEGIN
	SELECT 
		MA.CODMARCA AS `Value`,
		MA.NOMBREMARCA AS `Name`
	FROM MARCA AS MA;
END$$

-- CALL USP_SELECT_MARCAS();

-- GET ALL
CREATE PROCEDURE USP_GET_MARCA()
BEGIN
	SELECT 
		MA.CODMARCA,
		MA.NOMBREMARCA,
		MA.ESTMARCA
	FROM MARCA AS MA;
END$$

CALL USP_GET_MARCA();

-- GET BY ID
CREATE PROCEDURE USP_GET_ID_MARCA(IN CODMARCA INT)
BEGIN
	SELECT 
		MA.CODMARCA,
		MA.NOMBREMARCA,
        MA.ESTMARCA
	FROM MARCA AS MA
	WHERE MA.CODMARCA = CODMARCA
	  AND MA.ESTMARCA = 1;
END$$

-- CALL USP_GET_ID_MARCA(8);

---------------------------------------
--  		   PRODUCTO        	     --
---------------------------------------

--  GET ALL
CREATE PROCEDURE USP_GET_PRODUCTO()
BEGIN
    SELECT
        PR.CODPRODUCTO,
        CA.NOMCATEGORIA,
        MA.NOMBREMARCA,
        PR.IMGPRODUCTO,
        PR.NOMPRODUCTO,
        PR.DESCRIPCION,
        PR.PREUNI,
        PR.STOCK,
        PR.ESTPRODUCTO
    FROM PRODUCTO AS PR
    INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA = CA.CODCATEGORIA
    INNER JOIN MARCA MA ON PR.CODMARCA = MA.CODMARCA;
END$$

-- GET BY CATEGORIA
CREATE PROCEDURE USP_GET_PRODUCTO_POR_CATEGORIA(IN CodCategoria INT)
BEGIN
    SELECT 
        P.CODPRODUCTO,
        C.NOMCATEGORIA,
        P.IMGPRODUCTO,
        P.NOMPRODUCTO,
        P.DESCRIPCION,
        P.PREUNI,
        M.NOMBREMARCA,
        P.STOCK,
        P.ESTPRODUCTO
    FROM PRODUCTO P
    INNER JOIN CATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
    INNER JOIN MARCA M ON P.CODMARCA = M.CODMARCA
    WHERE P.CODCATEGORIA = CodCategoria;
END$$

-- CALL USP_GET_PRODUCTO_POR_CATEGORIA(1);

-- GET TOP 5
CREATE PROCEDURE USP_GET_TOP5_PRODUCTOS_MAS_BARATOS()
BEGIN
    SELECT
        P.CODPRODUCTO,
        C.NOMCATEGORIA,
        P.IMGPRODUCTO,
        P.NOMPRODUCTO,
        P.DESCRIPCION,
        P.PREUNI,
        M.NOMBREMARCA,
        P.STOCK,
        P.ESTPRODUCTO
    FROM PRODUCTO P
    INNER JOIN CATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
    INNER JOIN MARCA M ON P.CODMARCA = M.CODMARCA
    WHERE P.ESTPRODUCTO = 1
    ORDER BY P.PREUNI ASC
    LIMIT 5;
END$$

-- CALL USP_GET_TOP5_PRODUCTOS_MAS_BARATOS();

-- GET BY PEDIDO
CREATE PROCEDURE USP_GET_PRODUCTOS_POR_PEDIDO(IN CODPEDIDO INT)
BEGIN	
    SELECT
        P.IMGPRODUCTO,
        P.NOMPRODUCTO,
        D.PREUNI,
        D.CANTIDAD
    FROM DETALLEPEDIDO D
    INNER JOIN PRODUCTO P
        ON D.CODPRODUCTO = P.CODPRODUCTO 
    WHERE D.CODPEDIDO = CODPEDIDO;
END$$

-- CALL USP_GET_PRODUCTOS_POR_PEDIDO(1);

-- GET BY ID
CREATE PROCEDURE USP_GET_ID_PRODUCTO(IN CODPRODUCTO INT)
BEGIN
    SELECT
        PR.CODPRODUCTO,
        CA.NOMCATEGORIA,
        PR.IMGPRODUCTO,
        PR.NOMPRODUCTO,
        PR.DESCRIPCION,
        PR.PREUNI,
        MA.NOMBREMARCA,
        PR.STOCK,
        PR.ESTPRODUCTO
    FROM PRODUCTO AS PR
    INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA = CA.CODCATEGORIA
    INNER JOIN MARCA MA ON PR.CODMARCA = MA.CODMARCA
    WHERE PR.CODPRODUCTO = CODPRODUCTO;
END$$

-- CALL USP_GET_ID_PRODUCTO(3);

-- MERGE
CREATE PROCEDURE USP_MERGE_PRODUCTO(
    IN CODPRODUCTO INT,
    IN CODCATEGORIA INT,
    IN IMGPRODUCTO VARCHAR(50),
    IN NOMPRODUCTO VARCHAR(70),
    IN DESCRIPCION VARCHAR(300),
    IN PREUNI DECIMAL(10,2),
    IN CODMARCA INT,
    IN STOCK INT,
    IN ESTPRODUCTO BIT
)
BEGIN
    INSERT INTO PRODUCTO (
        CODPRODUCTO, CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI,
        CODMARCA, STOCK, ESTPRODUCTO
    ) VALUES (
        CODPRODUCTO, CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI,
        CODMARCA, STOCK, ESTPRODUCTO
    )
    ON DUPLICATE KEY UPDATE
        CODCATEGORIA = VALUES(CODCATEGORIA),
        IMGPRODUCTO = VALUES(IMGPRODUCTO),
        NOMPRODUCTO = VALUES(NOMPRODUCTO),
        DESCRIPCION = VALUES(DESCRIPCION),
        PREUNI = VALUES(PREUNI),
        CODMARCA = VALUES(CODMARCA),
        STOCK = VALUES(STOCK),
        ESTPRODUCTO = VALUES(ESTPRODUCTO);
END$$

-- DELETE
CREATE PROCEDURE USP_DELETE_PRODUCTO(IN p_CODPRODUCTO INT)
BEGIN
    UPDATE PRODUCTO
    SET ESTPRODUCTO = 0
    WHERE CODPRODUCTO = p_CODPRODUCTO;
END$$


-- ENABLE 
CREATE PROCEDURE USP_ENABLE_PRODUCTO(IN p_CODPRODUCTO INT)
BEGIN
    UPDATE PRODUCTO
    SET ESTPRODUCTO = 1
    WHERE CODPRODUCTO = p_CODPRODUCTO;
END$$

---------------------------------------
-- 		   ESTADO_PEDIDO   	         --
---------------------------------------

-- SELECT
CREATE PROCEDURE USP_SELECT_ESTADOS()
BEGIN
	SELECT 
		E.CODESTADO AS `Value`,
		E.NOMESTADO AS `Name`
	FROM ESTADO_PEDIDO E;
END$$

---------------------------------------
-- 		       PEDIDO   	         --
---------------------------------------

-- GET ALL
CREATE PROCEDURE USP_GET_PEDIDO()
BEGIN
	SELECT
		P.CODPEDIDO,
		P.FECPED,
		CONCAT(U.NOMUSUARIO, ' ', U.APEUSUARIO) AS CLIENTE,
		P.PRECIOTOTAL,
		E.NOMESTADO,
		SUM(D.CANTIDAD) AS CANTIDADTOTAL
	FROM PEDIDO P
	INNER JOIN USUARIO U ON P.CODUSUARIO = U.CODUSUARIO
	INNER JOIN ESTADO_PEDIDO E ON E.CODESTADO = P.CODESTADO
	INNER JOIN DETALLEPEDIDO D ON P.CODPEDIDO = D.CODPEDIDO
	GROUP BY P.CODPEDIDO, P.FECPED, U.NOMUSUARIO, U.APEUSUARIO, P.PRECIOTOTAL, E.NOMESTADO
	ORDER BY ABS(DATEDIFF(P.FECPED, NOW())) ASC, 
			 P.PRECIOTOTAL DESC;
END$$

-- CALL USP_GET_PEDIDO();

-- GET ONE
CREATE PROCEDURE USP_GET_ONE_PEDIDO(IN CODPEDIDO INT)
BEGIN
	SELECT
		A.CODPEDIDO,
		CONCAT(U.NOMUSUARIO, ' ', U.APEUSUARIO) AS CLIENTE,
		A.FECPED,
		A.PRECIOTOTAL,
		A.CODESTADO,
		A.ESTPED
	FROM PEDIDO A
	INNER JOIN USUARIO U ON A.CODUSUARIO = U.CODUSUARIO
	WHERE A.CODPEDIDO = CODPEDIDO
	ORDER BY A.FECPED DESC;
END$$

-- CALL USP_GET_ONE_PEDIDO(1);

-- INSERT
CREATE TABLE TMP_DETALLE_PEDIDO (
	CODPRODUCTO INT,
	PREUNI DECIMAL(10,2),
	CANTIDAD INT
);

CREATE PROCEDURE USP_INSERT_PEDIDODETALLE(
	IN CODUSUARIO INT,
	IN FECPED DATE,
	IN PRECIOTOTAL DECIMAL(10,2),
	IN CODESTADO INT,
	IN ESTPED BOOLEAN
)
BEGIN
	DECLARE CODPEDIDO INT;
	START TRANSACTION;

	INSERT INTO PEDIDO (CODUSUARIO, FECPED, PRECIOTOTAL, CODESTADO, ESTPED)
	VALUES (CODUSUARIO, FECPED, PRECIOTOTAL, CODESTADO, ESTPED);

	SET CODPEDIDO = LAST_INSERT_ID();

	INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD)
	SELECT CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD
	FROM TMP_DETALLE_PEDIDO;
	COMMIT;
END$$

-- TRUNCATE TMP_DETALLE_PEDIDO;

-- INSERT INTO TMP_DETALLE_PEDIDO (CODPRODUCTO, PREUNI, CANTIDAD) VALUES
-- (11, 2403.50, 40),
-- (5, 2420.50, 50),
-- (13, 323.55, 30);

-- CALL USP_INSERT_PEDIDODETALLE(1, '2023-01-02', 2024.5, 1, 1);

-- UPDATE
CREATE PROCEDURE USP_UPDATE_PEDIDO(
	IN CODPEDIDO INT,
	IN CODESTADO INT
)
BEGIN
	UPDATE PEDIDO
	SET CODESTADO = CODESTADO,
		ESTPED = 1
	WHERE CODPEDIDO = CODPEDIDO;
END$$

-- CALL USP_UPDATE_PEDIDO(1, 3);

-- DELETE
CREATE PROCEDURE USP_DELETE_PEDIDO(IN CODPEDIDO INT)
BEGIN
	UPDATE PEDIDO
	SET CODESTADO = 5,
		ESTPED = 0
	WHERE CODPEDIDO = CODPEDIDO;
END$$

-- CALL USP_DELETE_PEDIDO(1); 

DELIMITER ;

