DROP DATABASE IF EXISTS BD_SHOPMI;
CREATE DATABASE BD_SHOPMI;

/* TABLAS */

-- ROL
CREATE TABLE ROL
(
    CODROL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBREROL VARCHAR(100) NOT NULL,
    ESTROL BIT NOT NULL
);

-- USUARIO
CREATE TABLE USUARIO
(
	CODUSUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NUMERODOCUMENTO CHAR(8) NOT NULL,
	APEUSUARIO VARCHAR(50) NOT NULL,
	NOMUSUARIO VARCHAR(50) NOT NULL,
	FECNAC DATE NOT NULL,
	SEXUSUARIO CHAR(1) NOT NULL,
	TELUSUARIO CHAR(9) NOT NULL,
	CORUSUARIO VARCHAR(80) NOT NULL,
	CONUSUARIO VARCHAR(100) NOT NULL,
	FECCRE DATETIME NOT NULL DEFAULT NOW(),
	ESTUSUARIO BIT NOT NULL,
	CODROL INT NOT NULL,
	FOREIGN KEY (CODROL) REFERENCES ROL
);

-- CATEGORIA
CREATE TABLE CATEGORIA
(
    CODCATEGORIA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMGCATEGORIA VARCHAR(50) NOT NULL,
    NOMCATEGORIA VARCHAR(50) NOT NULL,
    ESTCATEGORIA TINYINT(1) NOT NULL
);

-- MARCA
CREATE TABLE MARCA
(
    CODMARCA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBREMARCA VARCHAR(25) NOT NULL,
    ESTMARCA TINYINT(1) NOT NULL
);

-- PRODUCTO
CREATE TABLE PRODUCTO
(
    CODPRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CODCATEGORIA INT NOT NULL,
    IMGPRODUCTO VARCHAR(50) NOT NULL,
    NOMPRODUCTO VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CODMARCA INT NOT NULL,
    STOCK INT NOT NULL,
    ESTPRODUCTO TINYINT(1) NOT NULL,
    FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA,
    FOREIGN KEY (CODMARCA) REFERENCES MARCA
);

-- ESTADO_PEDIDO
CREATE TABLE ESTADO_PEDIDO (
    CODESTADO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMESTADO VARCHAR(50) NOT NULL
);

-- PEDIDO
CREATE TABLE PEDIDO
(
    CODPEDIDO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CODUSUARIO INT NOT NULL,
    FECPED DATE NOT NULL,
	PRECIOTOTAL DECIMAL(10,2) NOT NULL,
	CODESTADO INT NOT NULL,
	ESTPED TINYINT(1) NOT NULL,
    FOREIGN KEY (CODUSUARIO) REFERENCES USUARIO,
	FOREIGN KEY (CODESTADO) REFERENCES ESTADO_PEDIDO
);

-- DETALLEPEDIDO
CREATE TABLE DETALLEPEDIDO
(
	CODPEDIDO INT NOT NULL,
	CODPRODUCTO INT NOT NULL,
	PREUNI DECIMAL(10, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	PRIMARY KEY(CODPEDIDO, CODPRODUCTO),
	FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDO,
	FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO
)




















