USE BD_SHOPMI;


/* INSERCIONES */

/* ROL */
INSERT INTO ROL (NOMBREROL, ESTROL) VALUES ('CLI', 1); -- Cliente
INSERT INTO ROL (NOMBREROL, ESTROL) VALUES ('VND', 1); -- Vendedor
INSERT INTO ROL (NOMBREROL, ESTROL) VALUES ('SPT', 1); -- Soporte

/* USUARIO */
INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('48392812', 'Ramírez Huamán', 'Carlos', '1985-05-20', 'H', '945123456', 'c.ramirez@empresa.com', 'Empleado123', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('40382920', 'Quispe Soto', 'Andrea', '1990-09-12', 'M', '981234567', 'a.quispe@empresa.com', 'Empleado123', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('40839201', 'Torres Medina', 'Luis', '1992-07-08', 'H', '912345678', 'l.torres@gmail.com', 'Cliente123', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('47829301', 'Alvarado Ruiz', 'Sofía', '1995-11-25', 'M', '987654321', 's.alvarado@hotmail.com', 'Cliente123', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('42918432', 'Gonzales Ríos', 'Martín', '1991-02-17', 'H', '956782341', 'martin.gr@correo.com', 'PassMart1', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('42123456', 'Vásquez López', 'Claudia', '1993-03-22', 'M', '967834122', 'claudia.vl@empresa.com', 'PassClau2', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('43128977', 'Cáceres Poma', 'Jorge', '1988-12-10', 'H', '976123456', 'jorge.cp@correo.com', 'PassJor3', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('45267891', 'Meza Huerta', 'Patricia', '1994-06-05', 'M', '912345879', 'patricia.mh@empresa.com', 'PassPat4', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('46278901', 'Rojas Tejada', 'Héctor', '1990-11-30', 'H', '964789132', 'hector.rt@empresa.com', 'PassHec5', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('49238721', 'Fernández Luján', 'Daniela', '1996-08-18', 'M', '986531278', 'daniela.fl@gmail.com', 'CliDani1', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('40239817', 'Medina Ríos', 'Sergio', '1991-01-04', 'H', '998123987', 'sergio.mr@gmail.com', 'CliSerg2', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('45819273', 'Guzmán Peñaloza', 'Andrea', '1998-02-09', 'M', '984561234', 'andrea.gp@hotmail.com', 'CliAnd3', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('41289347', 'Vega Salas', 'Ignacio', '1993-10-14', 'H', '971234987', 'ignacio.vs@yahoo.com', 'CliIgn4', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('48932175', 'Delgado Ramos', 'Lucía', '1997-04-28', 'M', '974321654', 'lucia.dr@gmail.com', 'CliLuc5', 1, 2);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('47892341', 'Peña Torres', 'Renato', '1987-03-16', 'H', '935612348', 'renato.pt@empresa.com', 'EmpRen6', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('46982734', 'Chávez Herrera', 'Valeria', '1990-12-07', 'M', '956123456', 'valeria.ch@empresa.com', 'EmpVal7', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('41327849', 'Aguilar Pinto', 'Miguel', '1989-08-01', 'H', '985634712', 'miguel.ap@empresa.com', 'EmpMig8', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('49731248', 'Navarro León', 'María', '1994-01-19', 'M', '963218745', 'maria.nl@empresa.com', 'EmpMar9', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('40321578', 'Campos Rivas', 'Enzo', '1992-05-22', 'H', '984513276', 'enzo.cr@empresa.com', 'EmpEnz10', 1, 1);

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('48821739', 'Morales Escobar', 'Valentina', '1999-09-03', 'H', '991234562', 'valentina.me@gmail.com', 'CliVal6', 1, 2);

/* CATEGORIA */
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('smartphones.jpg', 'Smartphones y Accesorios', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('computo.jpg', 'Laptops y Equipos de Cómputo', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('audio.jpg', 'Audio y Accesorios Bluetooth', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('gaming.jpg', 'Gaming y Consolas', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('hogar-inteligente.jpg', 'Hogar Inteligente y Domótica', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('fotografia.jpg', 'Cámaras y Fotografía Digital', 1);

/* MARCA */
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Apple', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Samsung', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Xiaomi', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Sony', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('HP', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Lenovo', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('DJI', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('GoPro', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Anker', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('TP-Link', 1);

/* PRODUCTO */

-- SMARTPHONES
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones1.jpg', 'iPhone 15 Pro Max 128GB', 'Smartphone de última generación con cámara de 48 MP y rendimiento excepcional', 1299.99, 1, 50, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones2.jpg', 'Samsung Galaxy S24 Ultra 256GB', 'Pantalla Dynamic AMOLED 2X, 5G, cámara de 200 MP y diseño premium', 1499.99, 2, 40, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones3.jpg', 'Xiaomi Redmi Note 13 Pro+ 5G', 'Smartphone 5G con procesador potente, pantalla de 120Hz y cámara de 200 MP', 499.99, 3, 60, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones4.jpg', 'Sony Xperia 1 IV', 'Smartphone con pantalla 4K OLED y cámara avanzada para video y fotografía', 1299.99, 4, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones5.jpg', 'HP Calc Pro X45', 'Smartphone de alto rendimiento con funciones avanzadas de cálculo, perfecto para estudiantes, ingenieros y profesionales que necesitan productividad', 799.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones6.jpg', 'Lenovo Legion Phone Duel 2', 'Smartphone gamer con dual cooling y pantalla de 144Hz', 999.99, 6, 35, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones7.jpg', 'Samsung Galaxy A55', 'Smartphone de gama media con pantalla Super AMOLED de 6.6", cámara triple de 50 MP y batería de 5000 mAh', 1699.99, 2, 45, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones8.jpg', 'Anker PowerCore 20000 mAh', 'Power bank de alta capacidad con carga rápida para smartphones', 49.99, 9, 120, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones9.jpg', 'Samsung Galaxy A35', 'Smartphone con pantalla Super AMOLED de 6.6", cámara de 50 MP y procesador Exynos 1380', 1299.99, 2, 100, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones10.jpg', 'Samsung Galaxy S20', 'Smartphone de gama alta con pantalla AMOLED de 6.2", cámara triple de 64 MP y grabación en 8K', 1999.99, 2, 80, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones11.jpg', 'Funda Antigolpes para iPhone 15 Pro Max', 'Funda resistente a golpes, elegante y ligera, ideal para proteger tu iPhone 15 Pro Max', 29.99, 1, 200, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones12.jpg', 'Cargador Rápido Samsung 25W USB-C', 'Cargador rápido original de 25W, ideal para todos los dispositivos Samsung', 24.99, 2, 150, 1);

-- COMPUTO
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo1.jpg', 'MacBook Air M2', 'Laptop ligera con chip Apple M2, ideal para productividad.', 1199.99, 1, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo2.jpg', 'MacBook Pro 14"', 'Potente laptop para profesionales con chip M3 y pantalla Liquid Retina.', 1999.99, 1, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo3.jpg', 'Samsung Galaxy Book3', 'Laptop ultradelgada con pantalla AMOLED y gran rendimiento.', 1099.99, 2, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo4.jpg', 'Xiaomi RedmiBook Pro 15', 'Laptop con pantalla 2.5K y procesador Ryzen 7.', 899.99, 3, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo5.jpg', 'Sony VAIO SX14', 'Laptop premium con diseño ligero y pantalla 4K.', 1499.99, 4, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo6.jpg', 'HP Pavilion x360', 'Laptop convertible con pantalla táctil y rendimiento versátil.', 799.99, 5, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo7.jpg', 'HP Victus Gaming', 'Laptop gamer con tarjeta gráfica dedicada y buen enfriamiento.', 999.99, 5, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo8.jpg', 'Lenovo IdeaPad 3', 'Laptop confiable para uso diario con excelente batería.', 649.99, 6, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo9.jpg', 'Lenovo Legion 5 Pro', 'Laptop para gaming con pantalla de alta tasa de refresco.', 1299.99, 6, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo10.jpg', 'Anker Docking Station', 'Estación de acoplamiento USB-C para laptops.', 149.99, 9, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo11.jpg', 'TP-Link Adaptador USB WiFi 6', 'Mejora tu conexión con este adaptador WiFi rápido.', 39.99, 10, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo12.jpg', 'DJI Wireless Mouse', 'Mouse inalámbrico con diseño ergonómico y precisión láser.', 59.99, 7, 14, 1);

-- AUDIO
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio1.jpg', 'AirPods Pro 2da Gen', 'Auriculares inalámbricos con cancelación activa de ruido.', 249.99, 1, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio2.jpg', 'Samsung Galaxy Buds2 Pro', 'Auriculares con sonido Hi-Fi y ANC.', 199.99, 2, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio3.jpg', 'Xiaomi Redmi Buds 4', 'Auriculares Bluetooth con buena autonomía y calidad.', 39.99, 3, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio4.jpg', 'Sony WH-1000XM5', 'Audífonos over-ear con cancelación de ruido líder en el mercado.', 349.99, 4, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio5.jpg', 'HP Bluetooth Headset 400', 'Auriculares ligeros para uso diario y llamadas.', 59.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio6.jpg', 'Lenovo LP40 Pro', 'Auriculares Bluetooth compactos con sonido envolvente.', 29.99, 6, 40, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio7.jpg', 'Anker Soundcore Life Q30', 'Auriculares con cancelación activa y batería de 40h.', 89.99, 9, 22, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio8.jpg', 'Anker Soundcore Liberty Air 2', 'Auriculares con micrófono dual y carga inalámbrica.', 99.99, 9, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio9.jpg', 'GoPro Pro 3.5mm Mic Adapter', 'Adaptador de audio para cámaras GoPro.', 49.99, 8, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio10.jpg', 'TP-Link UB500', 'Adaptador Bluetooth USB para conectar audio inalámbrico.', 19.99, 10, 35, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio11.jpg', 'DJI Mic', 'Micrófono inalámbrico profesional ideal para grabación de video.', 329.99, 7, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio12.jpg', 'Sony SRS-XB13', 'Mini parlante Bluetooth con Extra Bass y resistencia al agua.', 59.99, 4, 17, 1);

-- GAMING
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming1.jpg', 'PlayStation 5', 'Consola de nueva generación con SSD ultra rápido y gráficos envolventes.', 499.99, 4, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming2.jpg', 'Xbox Series X', 'Consola potente con capacidad 4K y biblioteca Xbox Game Pass.', 499.99, 5, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming3.jpg', 'Nintendo Switch OLED', 'Consola híbrida portátil con pantalla OLED y juegos exclusivos.', 349.99, 1, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming4.jpg', 'Mouse Gaming Logitech G502 HERO', 'Mouse ergonómico con sensor de alta precisión.', 59.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming5.jpg', 'HP OMEN 16', 'Laptop gamer con GPU dedicada y pantalla de alta frecuencia.', 1299.99, 5, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming6.jpg', 'Lenovo Legion Go', 'Consola portátil con sistema Windows para gaming completo.', 699.99, 6, 7, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming7.jpg', 'Mando Xbox Wireless', 'Control inalámbrico con agarre mejorado y compatibilidad amplia.', 59.99, 5, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming8.jpg', 'Anker Cargador Doble para Controles', 'Base de carga rápida para mandos de consola.', 39.99, 9, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming9.jpg', 'DJI GamePad Pro', 'Controlador ergonómico para juegos móviles y drones.', 89.99, 7, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming10.jpg', 'GoPro MAX', 'Cámara 360 ideal para grabaciones inmersivas en VR y gaming.', 499.99, 8, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming11.jpg', 'TP-Link Archer GX90', 'Router gaming con triple banda y optimización de latencia.', 229.99, 10, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming12.jpg', 'Sony INZONE H9', 'Auriculares gaming con cancelación de ruido y audio espacial.', 279.99, 4, 9, 1);

-- HOGAR INTELIGENTE
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar1.jpg', 'Apple HomePod Mini', 'Altavoz inteligente con Siri y sonido envolvente.', 99.99, 1, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar2.jpg', 'Samsung SmartThings Hub', 'Centro de control para dispositivos del hogar inteligente.', 89.99, 2, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar3.jpg', 'Xiaomi Sensor de Temperatura y Humedad', 'Sensor inteligente para monitoreo ambiental.', 19.99, 3, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar4.jpg', 'Sony Bravia XR OLED', 'Smart TV con inteligencia cognitiva y control por voz.', 1799.99, 4, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar5.jpg', 'HP Smart Tank 7305', 'Impresora inalámbrica con control vía app.', 289.99, 5, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar6.jpg', 'Lenovo Smart Clock 2', 'Reloj inteligente con pantalla táctil y Google Assistant.', 69.99, 6, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar7.jpg', 'DJI Mini 2 SE', 'Drone compacto con retorno automático y conexión a casa.', 399.99, 7, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar8.jpg', 'GoPro Hero como cámara de seguridad', 'Cámara versátil para vigilancia doméstica.', 299.99, 8, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar9.jpg', 'Anker Eufy Video Doorbell', 'Timbre inteligente con cámara y reconocimiento facial.', 179.99, 9, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar10.jpg', 'TP-Link Tapo C200', 'Cámara de seguridad Wi-Fi con visión nocturna.', 39.99, 10, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar11.jpg', 'TP-Link Tapo P100', 'Enchufe inteligente controlable desde el móvil.', 24.99, 10, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar12.jpg', 'Anker Eufy Smart Bulb', 'Foco inteligente con control por voz y app.', 29.99, 9, 20, 1);

-- FOTOGRAFIA
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia1.jpg', 'GoPro HERO12 Black', 'Cámara de acción con grabación 5.3K y estabilización avanzada.', 449.99, 8, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia2.jpg', 'Sony Alpha A7 III', 'Cámara mirrorless full-frame con enfoque automático preciso.', 1999.99, 4, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia3.jpg', 'DJI Osmo Pocket 2', 'Cámara portátil con estabilizador y calidad 4K.', 349.99, 7, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia4.jpg', 'HP Sprocket', 'Mini impresora fotográfica para móviles con conexión Bluetooth.', 129.99, 5, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia5.jpg', 'Anker Ring Light 10"', 'Aro de luz LED con soporte para selfies y grabaciones.', 49.99, 9, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia6.jpg', 'Lenovo 500 FHD Webcam', 'Cámara web Full HD para videollamadas y grabaciones.', 59.99, 6, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia7.jpg', 'TP-Link Tapo C325WB', 'Cámara exterior con ultra visión y tecnología ColorPro.', 109.99, 10, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia8.jpg', 'Samsung Galaxy Camera 2', 'Cámara compacta con Android y conectividad Wi-Fi.', 299.99, 2, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia9.jpg', 'iPhone 15 Pro - Modo Cinemático', 'Smartphone con cámara triple y grabación en ProRes.', 1199.99, 1, 14, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia10.jpg', 'Sony ZV-E10', 'Cámara ideal para vlogging con pantalla abatible y micrófono externo.', 749.99, 4, 7, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia11.jpg', 'DJI Mavic Air 2', 'Drone con cámara 4K y modos inteligentes de fotografía.', 799.99, 7, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia12.jpg', 'Xiaomi Mi 360° Home Camera 2K', 'Cámara de vigilancia con visión nocturna y control desde app.', 54.99, 3, 18, 1);

/* ESTADO PEDIDO */
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Pendiente');
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Pagado');
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Preparado');
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Procesado');
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Cancelado');
INSERT INTO ESTADO_PEDIDO (NOMESTADO) VALUES ('Entregado');

/* PEDIDO */
INSERT INTO PEDIDO (CODUSUARIO, FECPED, PRECIOTOTAL, CODESTADO, ESTPED) VALUES 
(1, '2025-03-01', 250.50, 1, 1),
(2, '2025-03-02', 180.00, 4, 1),
(3, '2025-03-03', 320.75, 6, 1),
(4, '2025-03-04', 95.30, 3, 0),
(5, '2025-03-05', 410.00, 2, 1),
(6, '2025-03-06', 212.99, 1, 1),
(7, '2025-03-07', 147.20, 2, 1),
(8, '2025-03-08', 305.50, 3, 1),
(9, '2025-03-09', 99.99, 5, 0),
(10, '2025-03-10', 525.00, 6, 1),
(11, '2025-03-11', 183.45, 5, 1),
(12, '2025-03-12', 289.70, 4, 1),
(13, '2025-03-13', 150.25, 2, 1),
(14, '2025-03-14', 198.99, 5, 0),
(15, '2025-03-15', 333.00, 3, 1),
(16, '2025-03-16', 268.40, 4, 1),
(17, '2025-03-17', 149.99, 2, 1),
(18, '2025-03-18', 440.10, 1, 1),
(19, '2025-03-19', 375.75, 1, 1),
(20, '2025-03-20', 295.30, 5, 0);

/* DETALLEPEDIDO */
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (1, 1, 12.80, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (1, 3, 12.40, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (2, 2, 10.00, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (2, 4, 34.00, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (3, 1, 9.70, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (4, 5, 20.80, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (5, 6, 70.45, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (5, 2, 11.00, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (6, 7, 50.10, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (6, 8, 60.70, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (7, 9, 30.20, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (7, 10, 50.20, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (8, 11, 80.90, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (8, 12, 15.90, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (9, 13, 59.50, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (9, 14, 60.50, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (10, 15, 10.50, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (10, 16, 32.00, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (10, 17, 23.00, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (10, 18, 60.00, 4);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (11, 1, 12.80, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (11, 3, 12.40, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (12, 2, 10.00, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (12, 4, 34.00, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (13, 1, 9.70, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (14, 5, 20.80, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (15, 6, 70.45, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (15, 2, 11.00, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (16, 7, 50.10, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (16, 8, 60.70, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (17, 9, 30.20, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (17, 10, 50.20, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (18, 11, 80.90, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (18, 12, 15.90, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (19, 13, 59.50, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (19, 14, 60.50, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (20, 15, 10.50, 2);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (20, 16, 32.00, 1);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (20, 17, 23.00, 3);
INSERT INTO DETALLEPEDIDO (CODPEDIDO, CODPRODUCTO, PREUNI, CANTIDAD) VALUES (20, 18, 60.00, 4);
