DROP DATABASE IF EXISTS productos_bd;
CREATE DATABASE productos_bd;
USE productos_bd;

CREATE TABLE CATEGORIA (
    CODCATEGORIA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMGCATEGORIA VARCHAR(50) NOT NULL,
    NOMCATEGORIA VARCHAR(50) NOT NULL,
    ESTCATEGORIA TINYINT(1) NOT NULL
);

CREATE TABLE MARCA (
    CODMARCA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBREMARCA VARCHAR(25) NOT NULL,
    ESTMARCA TINYINT(1) NOT NULL
);

CREATE TABLE PRODUCTO (
    CODPRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CODCATEGORIA INT NOT NULL,
    IMGPRODUCTO VARCHAR(50) NOT NULL,
    NOMPRODUCTO VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    PREUNI DECIMAL(10, 2) NOT NULL,
    CODMARCA INT NOT NULL,
    STOCK INT NOT NULL,
    ESTPRODUCTO TINYINT(1) NOT NULL,
    FOREIGN KEY (CODCATEGORIA) REFERENCES CATEGORIA(CODCATEGORIA),
    FOREIGN KEY (CODMARCA) REFERENCES MARCA(CODMARCA)
);


/* CATEGORIA */
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('smartphones.jpg', 'Smartphones y Accesorios', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('computo.jpg', 'Laptops y Equipos de Cómputo', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('audio.jpg', 'Audio y Accesorios Bluetooth', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('gaming.jpg', 'Gaming y Consolas', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('hogar-inteligente.jpg', 'Hogar Inteligente y Domótica', 1);
INSERT INTO CATEGORIA (IMGCATEGORIA, NOMCATEGORIA, ESTCATEGORIA) 
VALUES ('fotografia.jpg', 'Cámaras y Fotografía Digital', 1);

/* MARCA */
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Apple', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Samsung', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Xiaomi', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Sony', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('HP', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Lenovo', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('DJI', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('GoPro', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('Anker', 1);
INSERT INTO MARCA (NOMBREMARCA, ESTMARCA) VALUES ('TP-Link', 1);

/* PRODUCTO */

-- SMARTPHONES
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones1.jpg', 'iPhone 15 Pro Max 128GB', 'Smartphone de última generación con cámara de 48 MP y rendimiento excepcional', 1299.99, 1, 50, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones2.jpg', 'Samsung Galaxy S24 Ultra 256GB', 'Pantalla Dynamic AMOLED 2X, 5G, cámara de 200 MP y diseño premium', 1499.99, 2, 40, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones3.jpg', 'Xiaomi Redmi Note 13 Pro+ 5G', 'Smartphone 5G con procesador potente, pantalla de 120Hz y cámara de 200 MP', 499.99, 3, 60, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones4.jpg', 'Sony Xperia 1 IV', 'Smartphone con pantalla 4K OLED y cámara avanzada para video y fotografía', 1299.99, 4, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones5.jpg', 'HP Calc Pro X45', 'Smartphone de alto rendimiento con funciones avanzadas de cálculo, perfecto para estudiantes, ingenieros y profesionales que necesitan productividad', 799.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones6.jpg', 'Lenovo Legion Phone Duel 2', 'Smartphone gamer con dual cooling y pantalla de 144Hz', 999.99, 6, 35, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones7.jpg', 'Samsung Galaxy A55', 'Smartphone de gama media con pantalla Super AMOLED de 6.6", cámara triple de 50 MP y batería de 5000 mAh', 1699.99, 2, 45, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones8.jpg', 'Anker PowerCore 20000 mAh', 'Power bank de alta capacidad con carga rápida para smartphones', 49.99, 9, 120, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones9.jpg', 'Samsung Galaxy A35', 'Smartphone con pantalla Super AMOLED de 6.6", cámara de 50 MP y procesador Exynos 1380', 1299.99, 2, 100, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones10.jpg', 'Samsung Galaxy S20', 'Smartphone de gama alta con pantalla AMOLED de 6.2", cámara triple de 64 MP y grabación en 8K', 1999.99, 2, 80, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones11.jpg', 'Funda Antigolpes para iPhone 15 Pro Max', 'Funda resistente a golpes, elegante y ligera, ideal para proteger tu iPhone 15 Pro Max', 29.99, 1, 200, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (1, 'smartphones12.jpg', 'Cargador Rápido Samsung 25W USB-C', 'Cargador rápido original de 25W, ideal para todos los dispositivos Samsung', 24.99, 2, 150, 1);

-- COMPUTO
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo1.jpg', 'MacBook Air M2', 'Laptop ligera con chip Apple M2, ideal para productividad.', 1199.99, 1, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo2.jpg', 'MacBook Pro 14"', 'Potente laptop para profesionales con chip M3 y pantalla Liquid Retina.', 1999.99, 1, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo3.jpg', 'Samsung Galaxy Book3', 'Laptop ultradelgada con pantalla AMOLED y gran rendimiento.', 1099.99, 2, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo4.jpg', 'Xiaomi RedmiBook Pro 15', 'Laptop con pantalla 2.5K y procesador Ryzen 7.', 899.99, 3, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo5.jpg', 'Sony VAIO SX14', 'Laptop premium con diseño ligero y pantalla 4K.', 1499.99, 4, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo6.jpg', 'HP Pavilion x360', 'Laptop convertible con pantalla táctil y rendimiento versátil.', 799.99, 5, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo7.jpg', 'HP Victus Gaming', 'Laptop gamer con tarjeta gráfica dedicada y buen enfriamiento.', 999.99, 5, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo8.jpg', 'Lenovo IdeaPad 3', 'Laptop confiable para uso diario con excelente batería.', 649.99, 6, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo9.jpg', 'Lenovo Legion 5 Pro', 'Laptop para gaming con pantalla de alta tasa de refresco.', 1299.99, 6, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo10.jpg', 'Anker Docking Station', 'Estación de acoplamiento USB-C para laptops.', 149.99, 9, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo11.jpg', 'TP-Link Adaptador USB WiFi 6', 'Mejora tu conexión con este adaptador WiFi rápido.', 39.99, 10, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (2, 'computo12.jpg', 'DJI Wireless Mouse', 'Mouse inalámbrico con diseño ergonómico y precisión láser.', 59.99, 7, 14, 1);

-- AUDIO
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio1.jpg', 'AirPods Pro 2da Gen', 'Auriculares inalámbricos con cancelación activa de ruido.', 249.99, 1, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio2.jpg', 'Samsung Galaxy Buds2 Pro', 'Auriculares con sonido Hi-Fi y ANC.', 199.99, 2, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio3.jpg', 'Xiaomi Redmi Buds 4', 'Auriculares Bluetooth con buena autonomía y calidad.', 39.99, 3, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio4.jpg', 'Sony WH-1000XM5', 'Audífonos over-ear con cancelación de ruido líder en el mercado.', 349.99, 4, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio5.jpg', 'HP Bluetooth Headset 400', 'Auriculares ligeros para uso diario y llamadas.', 59.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio6.jpg', 'Lenovo LP40 Pro', 'Auriculares Bluetooth compactos con sonido envolvente.', 29.99, 6, 40, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio7.jpg', 'Anker Soundcore Life Q30', 'Auriculares con cancelación activa y batería de 40h.', 89.99, 9, 22, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio8.jpg', 'Anker Soundcore Liberty Air 2', 'Auriculares con micrófono dual y carga inalámbrica.', 99.99, 9, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio9.jpg', 'GoPro Pro 3.5mm Mic Adapter', 'Adaptador de audio para cámaras GoPro.', 49.99, 8, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio10.jpg', 'TP-Link UB500', 'Adaptador Bluetooth USB para conectar audio inalámbrico.', 19.99, 10, 35, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio11.jpg', 'DJI Mic', 'Micrófono inalámbrico profesional ideal para grabación de video.', 329.99, 7, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (3, 'audio12.jpg', 'Sony SRS-XB13', 'Mini parlante Bluetooth con Extra Bass y resistencia al agua.', 59.99, 4, 17, 1);

-- GAMING
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming1.jpg', 'PlayStation 5', 'Consola de nueva generación con SSD ultra rápido y gráficos envolventes.', 499.99, 4, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming2.jpg', 'Xbox Series X', 'Consola potente con capacidad 4K y biblioteca Xbox Game Pass.', 499.99, 5, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming3.jpg', 'Nintendo Switch OLED', 'Consola híbrida portátil con pantalla OLED y juegos exclusivos.', 349.99, 1, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming4.jpg', 'Mouse Gaming Logitech G502 HERO', 'Mouse ergonómico con sensor de alta precisión.', 59.99, 5, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming5.jpg', 'HP OMEN 16', 'Laptop gamer con GPU dedicada y pantalla de alta frecuencia.', 1299.99, 5, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming6.jpg', 'Lenovo Legion Go', 'Consola portátil con sistema Windows para gaming completo.', 699.99, 6, 7, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming7.jpg', 'Mando Xbox Wireless', 'Control inalámbrico con agarre mejorado y compatibilidad amplia.', 59.99, 5, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming8.jpg', 'Anker Cargador Doble para Controles', 'Base de carga rápida para mandos de consola.', 39.99, 9, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming9.jpg', 'DJI GamePad Pro', 'Controlador ergonómico para juegos móviles y drones.', 89.99, 7, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming10.jpg', 'GoPro MAX', 'Cámara 360 ideal para grabaciones inmersivas en VR y gaming.', 499.99, 8, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming11.jpg', 'TP-Link Archer GX90', 'Router gaming con triple banda y optimización de latencia.', 229.99, 10, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (4, 'gaming12.jpg', 'Sony INZONE H9', 'Auriculares gaming con cancelación de ruido y audio espacial.', 279.99, 4, 9, 1);

-- HOGAR INTELIGENTE
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar1.jpg', 'Apple HomePod Mini', 'Altavoz inteligente con Siri y sonido envolvente.', 99.99, 1, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar2.jpg', 'Samsung SmartThings Hub', 'Centro de control para dispositivos del hogar inteligente.', 89.99, 2, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar3.jpg', 'Xiaomi Sensor de Temperatura y Humedad', 'Sensor inteligente para monitoreo ambiental.', 19.99, 3, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar4.jpg', 'Sony Bravia XR OLED', 'Smart TV con inteligencia cognitiva y control por voz.', 1799.99, 4, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar5.jpg', 'HP Smart Tank 7305', 'Impresora inalámbrica con control vía app.', 289.99, 5, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar6.jpg', 'Lenovo Smart Clock 2', 'Reloj inteligente con pantalla táctil y Google Assistant.', 69.99, 6, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar7.jpg', 'DJI Mini 2 SE', 'Drone compacto con retorno automático y conexión a casa.', 399.99, 7, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar8.jpg', 'GoPro Hero como cámara de seguridad', 'Cámara versátil para vigilancia doméstica.', 299.99, 8, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar9.jpg', 'Anker Eufy Video Doorbell', 'Timbre inteligente con cámara y reconocimiento facial.', 179.99, 9, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar10.jpg', 'TP-Link Tapo C200', 'Cámara de seguridad Wi-Fi con visión nocturna.', 39.99, 10, 18, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar11.jpg', 'TP-Link Tapo P100', 'Enchufe inteligente controlable desde el móvil.', 24.99, 10, 30, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (5, 'hogar12.jpg', 'Anker Eufy Smart Bulb', 'Foco inteligente con control por voz y app.', 29.99, 9, 20, 1);

-- FOTOGRAFIA
INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia1.jpg', 'GoPro HERO12 Black', 'Cámara de acción con grabación 5.3K y estabilización avanzada.', 449.99, 8, 12, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia2.jpg', 'Sony Alpha A7 III', 'Cámara mirrorless full-frame con enfoque automático preciso.', 1999.99, 4, 6, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia3.jpg', 'DJI Osmo Pocket 2', 'Cámara portátil con estabilizador y calidad 4K.', 349.99, 7, 10, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia4.jpg', 'HP Sprocket', 'Mini impresora fotográfica para móviles con conexión Bluetooth.', 129.99, 5, 15, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia5.jpg', 'Anker Ring Light 10"', 'Aro de luz LED con soporte para selfies y grabaciones.', 49.99, 9, 25, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia6.jpg', 'Lenovo 500 FHD Webcam', 'Cámara web Full HD para videollamadas y grabaciones.', 59.99, 6, 20, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia7.jpg', 'TP-Link Tapo C325WB', 'Cámara exterior con ultra visión y tecnología ColorPro.', 109.99, 10, 8, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia8.jpg', 'Samsung Galaxy Camera 2', 'Cámara compacta con Android y conectividad Wi-Fi.', 299.99, 2, 9, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia9.jpg', 'iPhone 15 Pro - Modo Cinemático', 'Smartphone con cámara triple y grabación en ProRes.', 1199.99, 1, 14, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia10.jpg', 'Sony ZV-E10', 'Cámara ideal para vlogging con pantalla abatible y micrófono externo.', 749.99, 4, 7, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia11.jpg', 'DJI Mavic Air 2', 'Drone con cámara 4K y modos inteligentes de fotografía.', 799.99, 7, 5, 1);

INSERT INTO PRODUCTO (CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI, CODMARCA, STOCK, ESTPRODUCTO) 
VALUES (6, 'fotografia12.jpg', 'Xiaomi Mi 360° Home Camera 2K', 'Cámara de vigilancia con visión nocturna y control desde app.', 54.99, 3, 18, 1);

SELECT*FROM PRODUCTO;


-- ---------------------------------------------------
-- PROCEDIMIENTOS
-- ---------------------------------------------------
-- -------------------------------------
--          CATEGORIA                --
-- -------------------------------------

DELIMITER $$
CREATE PROCEDURE USP_SELECT_CATEGORIAS()
BEGIN
	SELECT
		CA.CODCATEGORIA AS `Value`,
		CA.NOMCATEGORIA AS `Name`
	FROM CATEGORIA AS CA;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_CATEGORIA()
BEGIN
	SELECT
		CA.CODCATEGORIA,
		CA.IMGCATEGORIA,
		CA.NOMCATEGORIA,
		CA.ESTCATEGORIA
	FROM CATEGORIA AS CA;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_ID_CATEGORIA(IN CODCATEGORIA INT)
BEGIN
	SELECT
		CA.CODCATEGORIA,
		CA.IMGCATEGORIA,
		CA.NOMCATEGORIA
	FROM CATEGORIA AS CA
	WHERE CA.CODCATEGORIA = CODCATEGORIA;
END$$
DELIMITER ;

-- -------------------------------------
--          MARCA                    --
-- -------------------------------------

DELIMITER $$
CREATE PROCEDURE USP_SELECT_MARCAS()
BEGIN
	SELECT
		MA.CODMARCA AS `Value`,
		MA.NOMBREMARCA AS `Name`
	FROM MARCA AS MA;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_MARCA()
BEGIN
	SELECT
		MA.CODMARCA,
		MA.NOMBREMARCA,
		MA.ESTMARCA
	FROM MARCA AS MA;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_ID_MARCA(IN CODMARCA INT)
BEGIN
	SELECT
		MA.CODMARCA,
		MA.NOMBREMARCA,
        MA.ESTMARCA
	FROM MARCA AS MA
	WHERE MA.CODMARCA = CODMARCA
	  AND MA.ESTMARCA = 1;
END$$
DELIMITER ;

--- ------------------------------------
--          PRODUCTO                 --
-- -------------------------------------

DELIMITER $$
CREATE PROCEDURE USP_GET_PRODUCTO()
BEGIN
    SELECT
        PR.CODPRODUCTO,
        CA.NOMCATEGORIA,
        MA.NOMBREMARCA AS nomMarca,
        PR.IMGPRODUCTO,
        PR.NOMPRODUCTO,
        PR.DESCRIPCION,
        PR.PREUNI,
        PR.STOCK,
        PR.ESTPRODUCTO
    FROM PRODUCTO AS PR
    INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA = CA.CODCATEGORIA
    INNER JOIN MARCA MA ON PR.CODMARCA = MA.CODMARCA;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_PRODUCTO_POR_CATEGORIA(IN CodCategoria INT)
BEGIN
    SELECT
        P.CODPRODUCTO,
        C.NOMCATEGORIA,
        P.IMGPRODUCTO,
        P.NOMPRODUCTO,
        P.DESCRIPCION,
        P.PREUNI,
        M.NOMBREMARCA AS nomMarca,
        P.STOCK,
        P.ESTPRODUCTO
    FROM PRODUCTO P
    INNER JOIN CATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
    INNER JOIN MARCA M ON P.CODMARCA = M.CODMARCA
    WHERE P.CODCATEGORIA = CodCategoria;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_TOP5_PRODUCTOS_MAS_BARATOS()
BEGIN
    SELECT
        P.CODPRODUCTO,
        C.NOMCATEGORIA,
        P.IMGPRODUCTO,
        P.NOMPRODUCTO,
        P.DESCRIPCION,
        P.PREUNI,
        M.NOMBREMARCA AS nomMarca,
        P.STOCK,
        P.ESTPRODUCTO
    FROM PRODUCTO P
    INNER JOIN CATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
    INNER JOIN MARCA M ON P.CODMARCA = M.CODMARCA
    WHERE P.ESTPRODUCTO = 1
    ORDER BY P.PREUNI ASC
    LIMIT 5;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_GET_ID_PRODUCTO(IN CODPRODUCTO INT)
BEGIN
    SELECT
        PR.CODPRODUCTO,
        CA.NOMCATEGORIA,
        PR.IMGPRODUCTO,
        PR.NOMPRODUCTO,
        PR.DESCRIPCION,
        PR.PREUNI,
        MA.NOMBREMARCA AS nomMarca,
        PR.STOCK,
        PR.ESTPRODUCTO
    FROM PRODUCTO AS PR
    INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA = CA.CODCATEGORIA
    INNER JOIN MARCA MA ON PR.CODMARCA = MA.CODMARCA
    WHERE PR.CODPRODUCTO = CODPRODUCTO;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_MERGE_PRODUCTO(
    IN CODPRODUCTO INT,
    IN CODCATEGORIA INT,
    IN IMGPRODUCTO VARCHAR(50),
    IN NOMPRODUCTO VARCHAR(70),
    IN DESCRIPCION VARCHAR(300),
    IN PREUNI DECIMAL(10,2),
    IN CODMARCA INT,
    IN STOCK INT,
    IN ESTPRODUCTO BIT
)
BEGIN
    INSERT INTO PRODUCTO (
        CODPRODUCTO, CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI,
        CODMARCA, STOCK, ESTPRODUCTO
    ) VALUES (
        CODPRODUCTO, CODCATEGORIA, IMGPRODUCTO, NOMPRODUCTO, DESCRIPCION, PREUNI,
        CODMARCA, STOCK, ESTPRODUCTO
    )
    ON DUPLICATE KEY UPDATE
        CODCATEGORIA = VALUES(CODCATEGORIA),
        IMGPRODUCTO = VALUES(IMGPRODUCTO),
        NOMPRODUCTO = VALUES(NOMPRODUCTO),
        DESCRIPCION = VALUES(DESCRIPCION),
        PREUNI = VALUES(PREUNI),
        CODMARCA = VALUES(CODMARCA),
        STOCK = VALUES(STOCK),
        ESTPRODUCTO = VALUES(ESTPRODUCTO);
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_DELETE_PRODUCTO(IN p_CODPRODUCTO INT)
BEGIN
    UPDATE PRODUCTO
    SET ESTPRODUCTO = 0
    WHERE CODPRODUCTO = p_CODPRODUCTO;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE USP_ENABLE_PRODUCTO(IN p_CODPRODUCTO INT)
BEGIN
    UPDATE PRODUCTO
    SET ESTPRODUCTO = 1
    WHERE CODPRODUCTO = p_CODPRODUCTO;
END$$
DELIMITER ;


