DROP DATABASE IF EXISTS usuarios_bd;
CREATE DATABASE usuarios_bd;
USE usuarios_bd;

CREATE TABLE ROL (
    CODROL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBREROL VARCHAR(100) NOT NULL,
    ESTROL BIT NOT NULL
);

CREATE TABLE USUARIO (
    CODUSUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NUMERODOCUMENTO CHAR(8) NOT NULL,
    APEUSUARIO VARCHAR(50) NOT NULL,
    NOMUSUARIO VARCHAR(50) NOT NULL,
    FECNAC DATE NOT NULL,
    SEXUSUARIO CHAR(1) NOT NULL,
    TELUSUARIO CHAR(9) NOT NULL,
    CORUSUARIO VARCHAR(80) NOT NULL,
    CONUSUARIO VARCHAR(100) NOT NULL,
    FECCRE DATETIME NOT NULL DEFAULT NOW(),
    ESTUSUARIO BIT NOT NULL,
    CODROL INT NOT NULL,
    FOREIGN KEY (CODROL) REFERENCES ROL(CODROL)
);

INSERT INTO ROL (NOMBREROL, ESTROL) VALUES ('CLIENTE', 1); 
INSERT INTO ROL (NOMBREROL, ESTROL) VALUES ('VENDEDOR', 1); 

select*from ROL;

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('48392812', 'Reyna Andrade', 'Sabrina', '2000-05-20', 'F', '945123456', 'sabrina@gmail.com', '$2a$12$Bm2r2N2YVwXK8rEBJ9SZ2ecRtNt.80hPIcG2M.1jE3HtussmNgNM6', 1, 2); -- contra 123

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('12345678', 'Lino Lagos', 'Mauro', '2000-03-10', 'M', '987000001', 'mauro@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 2);-- contra 123

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('12345679', 'Ataulluco Torres', 'Ashly', '2000-07-25', 'F', '987000002', 'ashly@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 2);-- contra 123

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('12345680', 'Tacanga Fernandez', 'Dante', '2000-09-01', 'M', '987000003', 'dante@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 2);-- contra 123

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('12345681', 'Tullume Prado', 'Manuel', '2000-12-12', 'M', '987000004', 'manuel@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 2);-- contra 123


INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('70111222', 'Pérez García', 'Juan', '1990-01-15', 'M', '987654321', 'juan.perez@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 1);-- contra 123

INSERT INTO USUARIO (NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC, SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO, ESTUSUARIO, CODROL)
VALUES ('70333444', 'López Díaz', 'María', '1995-11-30', 'F', '912345678', 'maria.lopez@gmail.com', '$2a$12$rBMKRJHduULER.TKpdV2yu/Ip8bDljh6wMl5X/JH2wp6Af6oWaWaW', 1, 1);-- contra 123

SELECT*FROM USUARIO;

-- ---------------------------------------------------
-- PROCEDIMIENTOS
-- ---------------------------------------------------

-- INSERTAR USUARIO USP_INSERT_USER
DELIMITER $$
CREATE PROCEDURE USP_INSERT_USER(
	IN NumeroDocumento CHAR(8),
	IN Apellido VARCHAR(50),
	IN Nombre VARCHAR(50),
	IN FechaNacimiento DATE,
	IN Sexo CHAR(1),
	IN Telefono CHAR(9),
	IN Correo VARCHAR(80),
	IN PasswordHash VARCHAR(100),
	IN Estado BIT,
	IN RolId INT,
	OUT NuevoId INT
)
BEGIN
	INSERT INTO USUARIO (
		NUMERODOCUMENTO, APEUSUARIO, NOMUSUARIO, FECNAC,
		SEXUSUARIO, TELUSUARIO, CORUSUARIO, CONUSUARIO,
		ESTUSUARIO, CODROL
	)
	VALUES (
		NumeroDocumento, Apellido, Nombre, FechaNacimiento,
		Sexo, Telefono, Correo, PasswordHash,
		Estado, RolId
	);
	SET NuevoId = LAST_INSERT_ID();
END$$
DELIMITER ;

---------------------------------------
--  USUARIO (GET por ID, para Pedidos) --
--  Se necesita para el Microservicio de Pedidos
---------------------------------------
DELIMITER $$
CREATE PROCEDURE USP_GET_USUARIO_POR_ID(IN CODUSUARIO INT)
BEGIN
	SELECT
		U.CODUSUARIO,
		U.APEUSUARIO,
		U.NOMUSUARIO
	FROM USUARIO AS U
	WHERE U.CODUSUARIO = CODUSUARIO;
END$$
DELIMITER ;


DELIMITER $$

CREATE PROCEDURE SP_InsertarUsuario(
    IN p_NUMERODOCUMENTO CHAR(8),
    IN p_APEUSUARIO VARCHAR(50),
    IN p_NOMUSUARIO VARCHAR(50),
    IN p_FECNAC DATE,
    IN p_SEXUSUARIO CHAR(1),
    IN p_TELUSUARIO CHAR(9),
    IN p_CORUSUARIO VARCHAR(80),
    IN p_CONUSUARIO VARCHAR(100)
)
BEGIN
    DECLARE v_existente INT;

    -- Verificar si ya existe un usuario con el mismo número de documento o correo
SELECT COUNT(*) INTO v_existente
FROM usuario
WHERE NUMERODOCUMENTO = p_NUMERODOCUMENTO
   OR CORUSUARIO = p_CORUSUARIO;

IF v_existente > 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'El usuario ya existe con ese documento o correo.';
ELSE
        INSERT INTO usuario (
            NUMERODOCUMENTO,
            APEUSUARIO,
            NOMUSUARIO,
            FECNAC,
            SEXUSUARIO,
            TELUSUARIO,
            CORUSUARIO,
            CONUSUARIO,
            FECCRE,
            ESTUSUARIO,
            CODROL
        )
        VALUES (
            p_NUMERODOCUMENTO,
            p_APEUSUARIO,
            p_NOMUSUARIO,
            p_FECNAC,
            p_SEXUSUARIO,
            p_TELUSUARIO,
            p_CORUSUARIO,
            p_CONUSUARIO,
            NOW(),
            1,
            1
        );
END IF;
END$$

DELIMITER ;






