server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true


      routes:
        - id: ms-producto
          uri: http://localhost:8081
          predicates:
            - Path=/api/productos/**

        - id: ms-pedido
          uri: http://localhost:8082
          predicates:
            - Path=/api/pedidos/**

        - id: ms-usuario
          uri: http://localhost:8083
          predicates:
            - Path=/api/usuarios/**
